server:
  port: 8081
  error:
    include-message: always

spring:
  # Configuraci贸n de migraci贸n con Flyway
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  # Configuraci贸n de la base de datos
  datasource:
    url: jdbc:postgresql://lallah.db.elephantsql.com:5432/pvenuzbu
    username: pvenuzbu
    password: 7omgWvebO1QdY4Wh-Us3pSXqt2E_qDtT
    driverClassName: org.postgresql.Driver

  # Configuraci贸n de JPA (Hibernate)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
